# src/config/settings.py

# Screen Config
SCREEN_RESOLUTION_W = 800
SCREEN_RESOLUTION_H = 480


# GPIO Pin Configuration (using BCM numbering)
RED_LED_PIN = 9
GREEN_LED_PIN = 11

EN_BUTTON_PIN = 24
MT_BUTTON_PIN = 17
PROTOCOL_BUTTON_PIN = 27
RESERVED_BUTTON_PIN = 4
STOP_BUTTON_PIN = 3
START_PAUSE_BUTTON_PIN = 2
SINGLE_PULSE_BUTTON_PIN = 25
ARROW_DOWN_BUTTON_PIN = 22
ARROW_UP_BUTTON_PIN = 18

BUTTONS = [EN_BUTTON_PIN, MT_BUTTON_PIN, PROTOCOL_BUTTON_PIN, RESERVED_BUTTON_PIN, STOP_BUTTON_PIN,
           START_PAUSE_BUTTON_PIN, SINGLE_PULSE_BUTTON_PIN, ARROW_DOWN_BUTTON_PIN, ARROW_UP_BUTTON_PIN]


CONTROL_ENC_P_PIN = 5
CONTROL_ENC_N_PIN = 6





# UART
HEADER_A = 0xFA
# HEADER_B = 0x55
UART_TX_SIZE = 16
UART_PORT = "/dev/ttyAMA0"
UART_BAUDRATE = 19200
UART_TIMEOUT = 0.2 
UART_RX_SIZE = 16

# Mode

IDLE = 0X00
SET_PARAMETERS = 0X01
START_STIMULATION = 0X02
STOP_STIMULATION = 0X03
PAUSE_STIMULATION = 0X04
STIMULATION_RUNNING = 0X05
ERROR = 0X06
MT = 0x07
SINGLE_PULSE = 0x08

# Application Settings
APP_NAME = "TMS Controller"
VERSION = "1.0.0"

# TMS Device Parameters
DEFAULT_PULSE_INTERVAL_MS = 1000


COIL_WARNING_TEMPERATURE_THRESHOLD = 35
COIL_DANGER_TEMPERATURE_THRESHOLD = 40

IGBT_WARNING_TEMPERATURE_THRESHOLD = 30
IGBT_DANGER_TEMPERATURE_THRESHOLD = 35

RESISTOR_WARNING_TEMPERATURE_THRESHOLD = 35
RESISTOR_DANGER_TEMPERATURE_THRESHOLD = 40


HARD_MAX_INTENSITY = 200